apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: sohampatil08/studentwar-database
    ports:
    - name: database
      protocol: TCP
      containerPort: 3306
    env:
    - name: MYSQL_DATABASE_NAME
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: DB_NAME
    - name: MYSQL_DATABASE_USER
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: DB_USER
    - name: MYSQL_DATABASE_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: DB_PASSWORD