apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pod
  template:
    metadata:
      name: my-pod
      labels:
        name: pod
        ENV: test
    spec: 
      containers:
      - name: c00
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP