apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name:pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  - name: apache-container
    image: apache2
    ports:
    - containerPort: 81
  - name: httpd-container
    image: httpd
    ports:
    - containerPort: 82