apiVersion: v1
kind: pod
metadata:
  name: pod1
spec:
  containers:
  - name: container
    image: nginx
    ports:
    - containerPort: 80
  containers:
  - name: container
    image: apache2
    ports:
    - containerPort: 81
    containers:
  - name: container
    image: httpd
    ports:
    - containerPort: 82