apiVersion: v1
kind: Namespace
metadata:
  name: new-namespace

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: new-namespace
spec:
  containers:
  - name: container
    image: nginx
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
