<<<<<<< HEAD
# mysql-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: sahilsapate08/database-studentwar
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 4321
        - name: MYSQL_DATABASE
          value: studentapp
---
# mysql-service.yml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
# tomcat-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: sahilsapate08/tomcat-studentwar
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: studentapp
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: 4321
=======
apiVersion: v1
kind: Namespace
metadata:
  name: new-namespace

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: new-namespace
spec:
  containers:
  - name: container
    image: nginx
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
>>>>>>> origin/main
