apiVersion: v1
kind: Namespace
metadata:
  name: b30

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: b30
spec:
  containers:
  - name: container
    image: nginx
    ports:
    - name: http
      containerPort: 80
      
