apiVersion: v1
kind: replicaController
metadata:
  name: my-replica
spec:
  replicas: 2
  
  template:
    metadata: 
      name: my-pod
      labels:
        name: pod1
    spec:
      containers:
      - name: c00
        image: nginx
