apiVersion: v1
kind: Replicaset
metadata:
  name: my-replica
spec:
  replicas: 2
  selector:
    matchExpression:
      - key: name
        operator: In
        value: pod
  template:
    metadata: 
      name: my-pod
      labels:
        name: pod
    spec:
      containers:
      - name: c00
        image: nginx