apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replica
spec:
  replicas: 2
  selector:
    name: pod1
  template:
    metadata: 
      name: my-pod
      labels:
        name: pod1
    spec:
      containers:
      - name: c00
        image: nginx