apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: name 
      operator: In 
      values: [pod]
    - key: job
      operator: In
      values: [test]
  template:
    metadata: 
      name: my-pod
      labels:
        name: pod
        job: test
    spec:
      containers:
      - name: c00
        image: nginx