apiVersion: v1
kind: Replicaset
metadata:
  name: my-replica
spec:
  replicas: 2
  selector:
    matchExpression:
      labels:
      - key
  template:
    metadata: 
      name: my-pod
      labels:
        name: pod1
    spec:
      containers:
      - name: c00
        image: nginx