apiVersion: v1
kind: Pod
metadata:
    name: pod
    labels:
      name: pod
      job: test
spec:
  containers:
  - name: container
    image: sohampatil08/studentwar-database
    ports:
    - name: database
      protocol: TCP
      containerPort: 3306
    env:
    - name: MYSQL_DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: "DB_NAME"
    - name: MYSQL_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: "DB_PASSWORD"
