apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: example-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: example-storage
  volumes:
    - name: example-storage
      persistentVolumeClaim:
        claimName: example-pvc
